UserAdmin/UserAdmin/Pages/AddContact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EdgeDB;
using Microsoft.AspNetCore.Identity;

namespace UserAdmin.Pages;

public class AddContactModel : PageModel
{
    [BindProperty]
    public List<Contact> ContactList { get;  set; } = new();
    [BindProperty]
    public InputContact contact { get;  set; }
    [BindProperty]
    public string SearchTerm { get; set; }

    private readonly EdgeDBClient _edgeDbClient;
    public AddContactModel(EdgeDBClient edgeDbClient)
    {
        _edgeDbClient = edgeDbClient;
    }
    public IActionResult OnPostLogout()
    {

        return RedirectToPage("/Index");
    }
    public IActionResult OnPostEdit(string username)
    {
        Console.WriteLine(username);
        return RedirectToPage("/EditContact", new { username });
    }


    public async Task<IActionResult> OnGetAsync()
    {
        SearchTerm = Request.Query["SearchTerm"].ToString();
        var query = "SELECT Contact { first_name, last_name, email, title, description, date_of_birth, marriage_status,user_name }";


        var result = await _edgeDbClient.QueryAsync<Contact>(query);


        foreach (var contact in result)
        {
              if (contact.first_name.Contains(SearchTerm) || contact.last_name.Contains(SearchTerm) || contact.email.Contains(SearchTerm))
                {
                    ContactList.Add(contact);
                }
            
        }
        return Page();
    }


    public async Task<IActionResult> OnPostAsync()
    {
        var passwordHasher = new PasswordHasher<string>();
        string hashedPassword = passwordHasher.HashPassword(null, contact.Password);
       

        var result = await _edgeDbClient.QueryAsync<Contact>(
    "INSERT Contact { first_name := <str>$first_name, last_name := <str>$last_name, user_name := <str>$user_name, email := <str>$email, title := <str>$title, password := <str>$password, role := <str>$role, description := <str>$description, date_of_birth := <str>$date_of_birth, marriage_status := <bool>$marriage_status }",
    new Dictionary<string, object>
    {
            { "first_name", contact.FirstName },
            { "last_name", contact.LastName },
            { "email", contact.Email },
            { "title", contact.Title },
            { "description", contact.Description },
            { "date_of_birth", contact.DateOfBirth },
            { "marriage_status", contact.MarriageStatus },
            { "role", contact.Role },
            { "user_name", contact.UserName},
            { "password", hashedPassword}
    });

        return Page();
    }
}

public class InputContact
{
    public string FirstName { get; set; } = " ";
    public string LastName { get; set; } = " ";
    public string Email { get; set; } = " ";
    public string Title { get; set; } = " ";
    public string Description { get; set; } = " ";
    public string DateOfBirth { get; set; } = " ";
    public string UserName { get; set; } = " ";
    public string Password { get; set; } = " ";
    public string Role { get; set; } = " ";
    public bool MarriageStatus { get; set; } = false;
}

UserAdmin/UserAdmin/Pages/EditContact.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EdgeDB;
using System.Text.Json;

namespace UserAdmin.Pages;

public class EditContactModel : PageModel
{
    private readonly EdgeDBClient _edgeDbClient;
  
    public Contact ContactTemp { get; set; }

    [BindProperty]
    public Contact ContactInput { get; set; }

    public EditContactModel(EdgeDBClient edgeDbClient)
    {
        _edgeDbClient = edgeDbClient;
    }


    public async Task<IActionResult> OnGetAsync(string username)
    {
       
        var query = "SELECT Contact {user_name, password,role ,first_name,last_name,description,title,marriage_status} " +
                       "FILTER Contact.user_name = <str>$username LIMIT 1;";

        var parameters = new Dictionary<string, object>
            {
                { "username", username }
            };
        
        var contact = await _edgeDbClient.QuerySingleAsync<Contact>(query, parameters);

     
        ContactTemp = contact;



        return Page();
    }


    public async Task<IActionResult> OnPostAsync()
    {

      
        string username = Request.Form["UserName"];
        ContactInput.first_name= Request.Form["FirstName"];
        ContactInput.last_name = Request.Form["LastName"];
        ContactInput.email = Request.Form["Email"];
        Console.WriteLine(ContactInput.first_name);

        var query = @"
                    UPDATE Contact
                    FILTER Contact.user_name = <str>$username
                    SET {
                        first_name := <str>$first_name,
                        last_name := <str>$last_name
                    }";
                            await _edgeDbClient.ExecuteAsync(query, new Dictionary<string, object?>
                    {
                        { "username", username },
                        { "first_name", ContactInput.first_name },
                        { "last_name", ContactInput.last_name }
                    });

        return RedirectToPage("/AddContact");
    }
}

UserAdmin/UserAdmin/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace UserAdmin.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

UserAdmin/UserAdmin/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using EdgeDB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace UserAdmin.Pages;

public class IndexModel : PageModel
{
    [BindProperty]
    public Login login { get; set; }

    public string role;

    private readonly EdgeDBClient _edgeDbClient;
    public IndexModel(EdgeDBClient edgeDbClient)
    {
        _edgeDbClient = edgeDbClient;
    }

    public async Task<IActionResult> OnPostAsync()
    {
        string username = login.UserName;
        string password = login.Password;

        var query = "SELECT Contact {user_name, password,role ,first_name,last_name,description,title,marriage_status} " +
                        "FILTER Contact.user_name = <str>$username AND Contact.password = <str>$password LIMIT 1;";


        var contact = await _edgeDbClient.QuerySingleAsync<Contact>(query, new Dictionary<string, object>
        {
            { "username", username },
            { "password", password }
        });


        if (contact == null)
        {
            ModelState.AddModelError("", "Invalid login");
            Console.WriteLine("No matching user found.");
            return Page();
        }

        if (contact != null)
        {

            return contact.role == "Admin" ? Redirect("/AddContact") : Redirect("/ViewUsers");
        }

        ModelState.AddModelError("", "Invalid login");
        Console.WriteLine("mafeesh");
        return Page();
    }
}

public class Contact
{
    public string first_name { get; set; } = " ";
    public string last_name { get; set; } = " ";
    public string email { get; set; } = " ";
    public string title { get; set; } = " ";
    public string description { get; set; } = " ";
    public string date_of_birth { get; set; } = " ";
    public string role { get; set; } = " ";
    public string user_name { get; set; } = " ";
    public string password { get; set; } = " ";
    public bool marriage_status { get; set; } = false;

}

public class Login
{
    public string UserName { get; set; } = " ";
    public string Password { get; set; } = " ";
    
}

UserAdmin/UserAdmin/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UserAdmin.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

UserAdmin/UserAdmin/Pages/ViewUsers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EdgeDB;
using Microsoft.AspNetCore.Identity;
namespace UserAdmin.Pages;

public class ViewUsersModel : PageModel
{
    [BindProperty]
    public List<Contact> ContactList { get; set; } = new();
    [BindProperty]
    public string SearchTerm { get; set; }

    private readonly EdgeDBClient _edgeDbClient;
    public ViewUsersModel(EdgeDBClient edgeDbClient)
    {
        _edgeDbClient = edgeDbClient;
    }
    public async Task<IActionResult> OnGetAsync()
    {
        SearchTerm = Request.Query["SearchTerm"].ToString();
        var query = "SELECT Contact { first_name, last_name, email, title, description, date_of_birth, marriage_status }";


        var result = await _edgeDbClient.QueryAsync<Contact>(query);


        foreach (var contact in result)
        {
            if (contact.first_name.Contains(SearchTerm) || contact.last_name.Contains(SearchTerm) || contact.email.Contains(SearchTerm))
            {
                ContactList.Add(contact);
            }

        }
        return Page();
    }

}

UserAdmin/UserAdmin/Pages/AddContact.cshtml
@page
@model UserAdmin.Pages.AddContactModel
@{
}

<body>

  <form method="post" asp-page-handler="Logout" style="position: absolute; top: 10px; right: 10px;">
    <input type="submit" value="Logout" style="background-color: darkred; color: white; font-weight: bold; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;">
</form>
    <div class="container">
        <form method="post">
            <label for="FirstName">First Name:</label>
            <input type="text" id="FirstName" name="FirstName" required>

             <label for="UserName">UserName Name:</label>
            <input type="text" id="UserName" name="UserName" required>

            <label for="LastName">Last Name:</label>
            <input type="text" id="LastName" name="LastName" required>

            <label for="Email">Email:</label>
            <input type="text" id="Email" name="Email" required>

            <label for="Title">Title:</label>
            <input type="text" id="Title" name="Title" required>

            <label for="Role">Role:</label>
            <input type="text" id="Role" name="Role" required>

            <label for="Description">Description:</label>
            <input type="text" id="Description" name="Description" required>

            <label for="DateOfBirth">Date of Birth:</label>
            <input type="text" id="DateOfBirth" name="DateOfBirth" required>

            <label for="MarriageStatus">Married:</label>
            <input type="checkbox" id="MarriageStatus" name="MarriageStatus" value="true">
            
            <label for="Password">Password:</label>
            <input type="password" id="Password" name="Password" required>

            <input type="submit" value="Add">
        </form>
    </div>
    
        <form method="get">
        <label for="SearchTerm">SearchTerm:</label>
        <input type="text" id="SearchTerm" name="SearchTerm">
        <input type="submit" value="Search">
    </form>
    
    <h2>Contact List</h2>

  <table>
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Title</th>
            <th>Description</th>
            <th>Date of Birth</th>
            <th>Role</th>
            <th>UserName</th>
            <th>Married</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
       @foreach (var contact in Model.ContactList)
{
    <tr>
        <td>@contact.first_name</td>
        <td>@contact.last_name</td>
        <td>@contact.email</td>
        <td>@contact.title</td>
        <td>@contact.description</td>
        <td>@contact.date_of_birth</td>
        <td>@contact.role</td>
        <td>@contact.user_name</td>
        <td>@(contact.marriage_status ? "Yes" : "No")</td>
        <td style="text-align: center; padding: 10px;">
        <form method="post" asp-page-handler="Edit">
                <input type="hidden" name="username" value="@contact.user_name" />
                <button type="submit">Edit</button>
            </form>

        </td>
    </tr>
}
    </tbody>
</table>


</body>

<style>
    .container {
        max-height: 400px;
        overflow-y: auto;
    }

    form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        width: 300px;
    }

    input[type="text"], input[type="checkbox"] {
        padding: 10px;
        margin: 10px;
        border-radius: 5px;
        background-color: #f1f1f1;
        width: 100%;
    }

    input[type="submit"] {
        padding: 10px;
        margin: 10px;
        border-radius: 5px;
        background-color: #4CAF50;
        color: #fff;
        font-weight: bold;
        cursor: pointer;
        width: 100%;
    }
</style>

UserAdmin/UserAdmin/Pages/EditContact.cshtml
@page "{username}"
@model UserAdmin.Pages.EditContactModel
@{
}

<body>

  <form method="post" asp-page-handler="Logout" style="position: absolute; top: 10px; right: 10px;">
    <input type="submit" value="Logout" style="background-color: darkred; color: white; font-weight: bold; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;">
  </form>

  <div class="container">
    <h2>Edit Contact</h2>
    <form method="post">
      <label for="FirstName">First Name:</label>
      <input type="text" id="FirstName" name="FirstName" asp-for="ContactTemp.first_name" required>

      <label for="UserName">UserName:</label>
      <input type="text" id="UserName" name="UserName" asp-for="ContactTemp.user_name" readonly>

      <label for="LastName">Last Name:</label>
      <input type="text" id="LastName" name="LastName" asp-for="ContactTemp.last_name" required>

      <label for="Email">Email:</label>
      <input type="text" id="Email" name="Email" asp-for="ContactTemp.email" >

      <label for="Title">Title:</label>
      <input type="text" id="Title" name="Title" asp-for="ContactTemp.title" >

      <label for="Role">Role:</label>
      <input type="text" id="Role" name="Role" asp-for="ContactTemp.role" >

      <label for="Description">Description:</label>
      <input type="text" id="Description" name="Description" asp-for="ContactTemp.description" >

      <label for="DateOfBirth">Date of Birth:</label>
      <input type="text" id="DateOfBirth" name="DateOfBirth" asp-for="ContactTemp.date_of_birth" >

      <label for="MarriageStatus">Married:</label>
      <input type="checkbox" id="MarriageStatus" name="MarriageStatus" asp-for="ContactTemp.marriage_status">

      <input type="submit" value="Save">
    </form>
  </div>

</body>

<style>
  .container {
    max-height: 400px;
    overflow-y: auto;
  }

  form {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 20px;
    background-color: #fff;
    border-radius: 10px;
    width: 300px;
  }

  input[type="text"],
  input[type="checkbox"] {
    padding: 10px;
    margin: 10px;
    border-radius: 5px;
    background-color: #f1f1f1;
    width: 100%;
  }

  input[type="submit"] {
    padding: 10px;
    margin: 10px;
    border-radius: 5px;
    background-color: #4CAF50;
    color: #fff;
    font-weight: bold;
    cursor: pointer;
    width: 100%;
  }
</style>

UserAdmin/UserAdmin/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<body>
        <div class="container">
            <form method="post">
                <label for="UserName">UserName:</label>
                <input type="text" id="UserName" name="UserName" required>

                <label for="Password">Password:</label>
                <input type="password" id="Password" name="Password" required>

                <input type="submit" value="Login">
            </form>
        </div>
</body>

<style>
    .container {
        max-width: 400px;
        display: block;
        padding: 10px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
    }
    input[type="text"], input[type="password"] {
        padding: 10px;
        margin: 10px;
        border-radius: 5px;
        background-color: #f1f1f1;
        width: 100%;
    }
    input[type="submit"] {
        padding: 10px;
        margin: 10px;
        border-radius: 5px;
        background-color: cornflowerblue;
        color: #fff;
        font-weight: bold;
        cursor: pointer;
        width: 100%;
    }
</style>

UserAdmin/UserAdmin/Pages/ViewUsers.cshtml
@page
@model UserAdmin.Pages.ViewUsersModel
@{
}

<body>

        <form method="get">
        <label for="SearchTerm">SearchTerm:</label>
        <input type="text" id="SearchTerm" name="SearchTerm">
        <input type="submit" value="Search">
        </form>
    
    <h2>Contact List</h2>

  <table>
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Title</th>
            <th>Description</th>
            <th>Date of Birth</th>
            <th>Role</th>
            <th>UserName</th>
            <th>Married</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
       @foreach (var contact in Model.ContactList)
{
    <tr>
        <td>@contact.first_name</td>
        <td>@contact.last_name</td>
        <td>@contact.email</td>
        <td>@contact.title</td>
        <td>@contact.description</td>
        <td>@contact.date_of_birth</td>
        <td>@contact.role</td>
        <td>@contact.user_name</td>
        <td>@(contact.marriage_status ? "Yes" : "No")</td>
        <td style="text-align: center; padding: 10px;"></td>
    </tr>
}
    </tbody>
</table>


</body>

<style>
    .container {
        max-height: 400px;
        overflow-y: auto;
    }

    form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        width: 300px;
    }

    input[type="text"], input[type="checkbox"] {
        padding: 10px;
        margin: 10px;
        border-radius: 5px;
        background-color: #f1f1f1;
        width: 100%;
    }

    input[type="submit"] {
        padding: 10px;
        margin: 10px;
        border-radius: 5px;
        background-color: #4CAF50;
        color: #fff;
        font-weight: bold;
        cursor: pointer;
        width: 100%;
    }
</style>